name: cs290v_mujoco
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - scipy
  - pip
  - pip:
      - mujoco
      - mujoco-python-viewer
      - torch
      - torchvision
      - torchaudio
      - pygame